# Game Modes
gamemodes:
- AcidIsland
- BSkyBlock
- CaveBock

# General block limiting
# Use this section to limit how many blocks can be added to an island.
# 0 means the item will be blocked from placement completely.
# These limits apply to every world
blocklimits:
  HOPPER: 10
# This section is for world-specific limits and overrides the general limit
# Specify each world you want to limit individually (including nether and end worlds)
worlds:
  AcidIsland_world:
    HOPPER: 11

# NOT IMPLEMENTED YET
entitylimits:
  # Mobs, animals and other living entities
  #BAT: 10
  #BLAZE: 10
  #BOAT: 10
  #CAVE_SPIDER: 10
  #CHICKEN: 10
  #COW: 10
  #CREEPER: 10
  #DONKEY: 10
  #ENDERMAN: 10
  #HORSE: 10
  #HUSK: 10
  #IRON_GOLEM: 10
  #LLAMA: 10
  #MAGMA_CUBE: 10
  #MULE: 10
  #MUSHROOM_COW: 10
  #OCELOT: 10
  #PIG: 10
  #PIG_ZOMBIE: 10
  #POLAR_BEAR: 10
  #RABBIT: 10
  #SHEEP: 10
  #SKELETON: 10
  #SKELETON_HORSE: 10
  #SLIME: 10
  #SNOWMAN: 10
  #SPIDER: 10
  #SQUID: 10
  #STRAY: 10
  #WITCH: 10
  #WITHER: 10
  #WITHER_SKELETON: 10
  #WOLF: 10
  #ZOMBIE: 10
  #ZOMBIE_HORSE: 10
  #ZOMBIE_VILLAGER: 10  
